# Generated by Django 4.1.7 on 2023-03-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
        ('Celebrity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrityComment', models.TextField()),
                ('recommendedDate', models.DateTimeField()),
                ('source', models.URLField()),
                ('Celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Celebrity.celebrity')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.books')),
            ],
        ),
    ]
