# Generated by Django 4.1.7 on 2023-07-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Celebrity', '0001_initial'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity_comment', models.TextField(blank=True, null=True)),
                ('Celebrity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebritys', to='Celebrity.celebrity')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Books.books')),
            ],
        ),
    ]
