# Generated by Django 4.1.7 on 2023-05-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_books_amazonlink_delete_affillatelink'),
        ('Celebrity', '0001_initial'),
        ('Recommend', '0003_alter_recommend_celebrity_alter_recommend_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='Celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Celebrity.celebrity'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.books'),
        ),
    ]
