# Generated by Django 4.1.7 on 2023-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Celebrity', '0001_initial'),
        ('Recommend', '0005_alter_recommend_celebrity_alter_recommend_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='Celebrity',
        ),
        migrations.AddField(
            model_name='recommend',
            name='Celebrity',
            field=models.ManyToManyField(related_name='celebritys', to='Celebrity.celebrity'),
        ),
    ]
