# Generated by Django 4.1.7 on 2023-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommend', '0006_remove_recommend_celebrity_recommend_celebrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='celebrityComment',
            field=models.TextField(null=True),
        ),
    ]
