# Generated by Django 4.1.7 on 2023-05-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommend', '0007_alter_recommend_celebritycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='celebrityComment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
