# Generated by Django 4.1.7 on 2023-05-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Celebrity', '0003_alter_celebrity_name_slug_alter_profession_name_slug'),
        ('Recommend', '0008_alter_recommend_celebritycomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='celebrityComment',
            new_name='celebrity_comment',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='Celebrity',
        ),
        migrations.AddField(
            model_name='recommend',
            name='Celebrity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebritys', to='Celebrity.celebrity'),
        ),
    ]
