# Generated by Django 4.1.7 on 2023-07-14 21:25

import Books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Celebrity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Books.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=100)),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Celebrity.celebrity')),
                ('categories', models.ManyToManyField(blank=True, to='Books.categories')),
                ('sub_categories', models.ManyToManyField(blank=True, to='Books.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=100)),
                ('amazonlink', models.URLField(default='https://amzn.to/3MquoAM')),
                ('dateOfPublish', models.DateField(null=True)),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Celebrity.celebrity')),
                ('categories', models.ManyToManyField(blank=True, to='Books.categories')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.series')),
                ('sub_categories', models.ManyToManyField(blank=True, to='Books.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=Books.models.get_upload_path)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.books')),
            ],
        ),
    ]
