# Generated by Django 4.1.7 on 2023-05-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='ratings',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
