# Generated by Django 4.1.7 on 2023-05-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_remove_books_ratings_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='amazonlink',
            field=models.URLField(default='https://amzn.to/3MquoAM'),
        ),
        migrations.DeleteModel(
            name='AffillateLink',
        ),
    ]
