# Generated by Django 4.1.7 on 2023-05-27 19:23

import Books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_books_amazonlink_delete_affillatelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='name_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookimages',
            name='image',
            field=models.FileField(blank=True, upload_to=Books.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='books',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='Books.categories'),
        ),
        migrations.AlterField(
            model_name='books',
            name='dateOfPublish',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='SubCategories',
            field=models.ManyToManyField(null=True, to='Books.subcategory'),
        ),
    ]
