# Generated by Django 4.1.7 on 2023-05-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_books_name_slug_categories_name_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Books.categories'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='SubCategories',
            field=models.ManyToManyField(blank=True, to='Books.subcategory'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
