# Generated by Django 4.1.7 on 2023-05-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_books_categories_alter_books_name_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=256)),
                ('authorName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=100)),
                ('categories', models.ManyToManyField(blank=True, to='Books.categories')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.series'),
        ),
    ]
