# Generated by Django 4.1.7 on 2023-06-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Celebrity', '0004_alter_socialplatform_name'),
        ('Books', '0006_series_books_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='authorName',
        ),
        migrations.AddField(
            model_name='books',
            name='author_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Celebrity.celebrity'),
        ),
    ]
