# Generated by Django 4.1.7 on 2023-06-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_remove_series_authorname_series_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, to='Books.subcategory'),
        ),
    ]
