# Generated by Django 4.1.7 on 2023-06-17 13:42

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_books_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='sub_categories',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='categories', chained_model_field='Categories', horizontal=True, to='Books.subcategory', verbose_name='Sub Category'),
        ),
    ]
