# Generated by Django 4.1.7 on 2023-06-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0011_alter_books_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='SubCategories',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Books.categories'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
