# Generated by Django 4.1.7 on 2023-07-14 21:25

import Celebrity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, upload_to=Celebrity.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER'), ('FACEBOOK', 'FACEBOOK'), ('LINKEDIN', 'LINKEDIN')], max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('Celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Celebrity.celebrity')),
            ],
        ),
        migrations.AddField(
            model_name='celebrity',
            name='professions',
            field=models.ManyToManyField(to='Celebrity.profession'),
        ),
    ]
