# Generated by Django 4.1.7 on 2023-03-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER'), ('FACEBOOK', 'FACEBOOK')], max_length=100)),
                ('link', models.URLField()),
                ('Celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Celebrity.celebrity')),
            ],
        ),
        migrations.AddField(
            model_name='celebrity',
            name='professions',
            field=models.ManyToManyField(to='Celebrity.profession'),
        ),
    ]
