# Generated by Django 4.1.7 on 2023-05-27 19:23

import Celebrity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Celebrity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='name_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='image',
            field=models.FileField(blank=True, upload_to=Celebrity.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='socialplatform',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
