# Generated by Django 4.1.7 on 2023-05-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Celebrity', '0002_celebrity_name_slug_profession_name_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='name_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
