# Generated by Django 4.1.7 on 2023-06-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Celebrity', '0003_alter_celebrity_name_slug_alter_profession_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='name',
            field=models.CharField(choices=[('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER'), ('FACEBOOK', 'FACEBOOK'), ('LINKEDIN', 'LINKEDIN')], max_length=100),
        ),
    ]
