# Generated by Django 4.1.7 on 2023-06-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Celebrity', '0004_alter_socialplatform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
